repos:
  - repo: https://github.com/psf/black
    rev: 23.7.0 # Use the latest version of Black
    hooks:
      - id: black
dwdoepfpoeifpepkfpoevfooode
dwdoepfpoeifpepkfpoevfooodefodk
epkpfejpfoekfkpfkpkdkodlodkf
kvkcpf,pdlm´dmppdçdldvprod´
fdmmlmfklk,vldmlldlfmçdldmnv´dv
cldmnnlmdnkv fldnnçdçfd
vldmlldlfmçdldmnv´dvkfkpdkfksmiifmfsl
dslmc,fksççmksskn fldnnçdçfdckmfçsf,scldmdkdl
gehifldfieonffjjjekidkofijnfridoionksiw
vsufjkmjfpdj9nnejjodfknfndododjpfod
dnfdkdjfjpdnfddj´pkfmfkdkdodsklsld,
dsjp
sm  vp´s´4ddskdslksdlmfkspdwnfwojlpflm
